version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run: apt update
      - run: apt upgrade -y
      - run: apt install -y cmake make gcc g++ git
      - run: git submodule update --init --recursive
      - run: mkdir build;cd build;cmake ..;make -j8
      - store_artifacts:
          path: build/bin
      - store_artifacts:
          path: build/lib